print("Homo habilis")
print("Homo rudolfensis")
print("Homo erectus")
print("Homo neanderthalensis")	
print("Homo sapiens sapiens\n")

print("Enter stadies of evolution in order")
print("First")
a=input()
print("Second")
b=input()
print("Third")
c=input()
print("Fourth")
d=input()
print(a,b,c,d,sep="=>")